### ISSUE TITLE
Error when executing vendor_signing.sh

### ISSUE THREAD

**Issue by dariodeltemple** [project-imas/mdm-server#21]
Hi,

I am stuck in step 4. of the **Certificate Setup** when I execute  vendor_signing.sh in the /scripts directory I get the following Java exception (after the warnings):

Test.java:23: warning: sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
import sun.misc.BASE64Encoder;
               ^
Test.java:51: warning: sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
                BASE64Encoder b64en = new BASE64Encoder();
                ^
Test.java:51: warning: sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
                BASE64Encoder b64en = new BASE64Encoder();
                                          ^
Test.java:152: warning: sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
                BASE64Encoder b64en = new BASE64Encoder();
                ^
Test.java:152: warning: sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
                BASE64Encoder b64en = new BASE64Encoder();
                                          ^
5 warnings
/home/ubuntu/mdm-server/mdm-server-master/vendor-signing/com/softhinker/vendor.p12
Exception in thread "main" java.io.IOException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1304)
        at java.security.KeyStore.load(KeyStore.java:1214)
        at com.softhinker.Test.extractPrivateKey(Test.java:98)
        at com.softhinker.Test.main(Test.java:54)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:811)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:676)
        at com.sun.crypto.provider.PKCS12PBECipherCore.implDoFinal(PKCS12PBECipherCore.java:355)
        at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineDoFinal(PKCS12PBECipherCore.java:462)
        at javax.crypto.Cipher.doFinal(Cipher.java:1922)
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1295)
        ... 3 more

Thanks in advance!

**Comment by dariodeltemple** [comment]
I just did the whole process again, starting from scratch downloading again the mdm-server files in this project, revoking and creating the MDM CSR certifcate at Apple's ios dev. portal and it worked.

Not sure what might be the cause of the issue. At first I had Java 7 installed, then I moved to Java 6. The other thing I did different is I used the same password for everything: pem pass phrase, challenge passwords and export password.

**Comment by thrasr** [comment]
Hi dariodeltemple,

Glad you got it working!

Unfortunately, the java code hasn't been updated to work with the latest versions of Java.  For anyone else with this issue, its best to use an older version of Java or look into [this python implementation](https://github.com/grinich/mdmvendorsign) in order to get the vendor signing process done.
