### ISSUE TITLE
InstallProvisioningProfile failed

### ISSUE THREAD

**Issue by BoydYang** [project-imas/mdm-server#48]
ADDED COMMAND TO QUEUE: 59cbc782-86b1-418e-abba-b46d76883824
*Adding CMD: 59cbc782-86b1-418e-abba-b46d76883824 to device: 6b4c248dbb695c2313226f1e715e61f5d6761a35
STORING DEVICES...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 239, in process
    return self.handle()
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python2.7/dist-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/byang/mdm-server/server/server.py", line 495, in POST
    return json.dumps(out)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Data(

**Comment by BoydYang** [comment]
it's a device populate problem
